export const SET_CUSTOMERS_LIST = 'SET_CUSTOMERS_LIST';
export const SET_CUSTOMERS_SEARCH_FIELD = 'SET_CUSTOMERS_SEARCH_FIELD';
export const SET_CREATE_CUSTOMER_DATA = 'SET_CREATE_CUSTOMER_DATA';
export const SET_CUSTOMERS_PAGINATION = 'SET_CUSTOMERS_PAGINATION';
export const SET_CUSTOMERS_SORT = 'SET_CUSTOMERS_SORT';
