export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDERS_SEARCH_FIELD = 'SET_ORDERS_SEARCH_FIELD';
export const SET_ORDER_DATA = 'SET_ORDER_DATA';
export const CLEAR_ORDER_DATA = 'CLEAR_ORDER_DATA';
