export const SET_USERS_LIST = 'SET_USERS_LIST';
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const SET_CREATE_DATA = 'SET_CREATE_DATA';
export const CLEAR_CREATE_DATA = 'CLEAR_CREATE_DATA';
